services:
  db:
    image: postgres:15
    container_name: car_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: car_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432

  redis:

    image: redis:7
    container_name: car_redis

  car_app:
    image: car_image
    build:
      context: .
    env_file:
      - .env
    container_name: car_app
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
#      grafana:
#        condition: service_started
#      prometheus:
#        condition: service_started
    command: ["/auto_app/docker/app.sh"]
    ports:
      - 8000:8000