global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['85.92.111.149:9090']

  - job_name: 'car_app'

    scrape_interval: 5s

    static_configs:
      - targets: ['car_app:8000']